[package]
name = "iox2-log-archive-core"
description = "High-rate archive recorder/replayer core for iceoryx2 data"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
default = ["std"]
std = ["dep:crc32c", "dep:getrandom"]

[dependencies]
crc32c = { workspace = true, optional = true }
getrandom = { version = "0.2.15", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.3"
libc = "0.2"

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
tempfile = { workspace = true }
